# Data Science Bootcamp  - Intro to Python

This notebook will go through the following topics:
 - Python Data Structures
 - Loops and Flow Controls
 - Importing a module

## Python Data Structures

#### Comments

In [57]:
# This is a single line comment. Use a hash at the start of the line to comment

"""
You can make multi-line comments by 
using a set of three double quote marks.


To run this cell press Shift+Enter
"""

'\nYou can make multi-line comments by \nusing a set of three double quote marks.\n\n\nTo run this cell press Shift+Enter\n'

#### Variables

In [12]:
# We can define variables without having to declare their type
x = 4.0
print (x)
# and you can change the value of a variable as often as you want
x = 3
print (x)
# you can increment variables like this:
x +=2 #this adds 2 to x

4.0
3


In [15]:
# you can increment variables like this:
x +=2 #this adds 2 to x (this is a shortcut to x = x + 2)
print (x)
#keep running this cell to see

11


#### Number Types

In [58]:
# Integers (int) are a numerical datatype
print(1+2)

3


In [59]:
#Floats are another, that allow decimels
print (1.0+5)
print (3.0-2.0)

6.0
1.0


##### Strings

In [61]:
# A string is a sequence of characters
print ('Yellow team is best!')
# and can be defined by either single or double quotes as long as you are consistant
print ("Blue team are ok too, I guess")

Yellow team is best!
Blue team are ok too, I guess


In [62]:
#And of course you can assign this to a variable
message = 'One team, one love...'
print (message)

One team, one love...


In [63]:
#And you can add strings together
string = message + "for the mother's pride, "
another_string = string + "for the times we cried..."
print (another_string)

One team, one love...for the mother's pride, for the times we cried...


#### Booleans

In [64]:
# Booleans are either True or False
x = True
y = False

print (x) # x is True
print (not x) # x is True, so not x is False
print (x and y) # this returns True is x and y are True
print (x and not y)
print (x or y) #returns True if x or y are true

True
False
False
True
True


#### Comparisons

In [28]:
# '==' checks if both sides are equal
print (1==2)
print (1==1)

False
True


In [29]:
# '!='checks if they are not equal
print (1 != 2)
print (1 != 1)

True
False


In [66]:
#This can also be done with strings
print('abcd' == 'abc')

False


In [67]:
x = 5
y = 10

print (x == y)

False


#### Lists

Lists allow us to store and access data, they are defined by square bracket [] and values are separated by commas. They can contain any type of value and can be mixed. 

In [29]:
list_1 = [] #note we shouldn't name the list as list is a function in Python
print(list_1)

x = 5
list_2 = [1,2.0,'a',"abcd",True,x] #a list can take multiple datatypes
print (list_2)

[]
[1, 2.0, 'a', 'abcd', True, 5]


In [30]:
#We can append values to a list 
list_1.append(1)
print(list_1)

[1]


In [31]:
list_1.append(list_2) #what would this do?
print (list_1)

[1, [1, 2.0, 'a', 'abcd', True, 5]]


In [32]:
list_1.extend(list_2) #what is the difference here?
print (list_1)

[1, [1, 2.0, 'a', 'abcd', True, 5], 1, 2.0, 'a', 'abcd', True, 5]


In [33]:
#accessing the data
list_1[3] #which element does this take, note Python starts with index of 0

2.0

In [50]:
#we can access the end of the list too
list_1[-3]

'abcd'

In [56]:
#and a subset
print(list_1[:4])
print(list_1[0:2])

[1, [1, 2.0, 'a', 'abcd', True, 5], 1, 2.0]
[1, [1, 2.0, 'a', 'abcd', True, 5]]


### Loops and flow control

We can use loops to control how the script runs. Booleans are used to control the flow. 

NOTE: Indentatations are really important in Python. 

#### if statements

In [34]:
flag = False
if flag:
    x = 1
    print ("Flag is True")
else:
    x = 2
    print ("Flag is False")
print (x)

Flag is False
2


In [35]:
if x == 0:
    print ('A')
elif x == 1:
    print ('B')
else:
    print('C')

C


#### For Loops

For loops allow us run a block of code a certain number of times

In [68]:
blue_team =  ['Jan', 'Matt','Jonathan','Tan','Wayne','Michal','Callum']

for member in blue_team:
    print(member)

Jan
Matt
Jonathan
Tan
Wayne
Michal
Callum


In [69]:
for i in range(len(blue_team)):
    print (blue_team[i])

Jan
Matt
Jonathan
Tan
Wayne
Michal
Callum


In [70]:
for i, member in enumerate(blue_team):
    print (str(i) + ": " + member)

0: Jan
1: Matt
2: Jonathan
3: Tan
4: Wayne
5: Michal
6: Callum


#### List Comprehension

List Comprehension allows you to create a list based on existing lists. Often this can be done in a loop, however list comprehension let's you do this in a very short and quick way.

In [55]:
#Let us create a range of numbers between 1 and 10o
a=[]
a=range(1,100)
print(list(a))

#We now want to take this list and create another list, with some manipulation and criteria
b=[2*i for i in a if i<50]
print(b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


#### Dictionaries

Dictionaries, called "dicts" for short, allow you to store values by providing identifying keys and values. they always have key/value pairs. Dicts are initialized using "{}". Placing a comma-separated list of key:value pairs within the braces addes initial key:value pairs to the dictionary. Dictionaries are indexed by keys instead of numeric indices.

NOTE: Dictionaries don't have an order - so you cannot rely on them to be in the same order as you expect them to be

In [45]:
d = {}
d = {'Blue': blue_team, 
     'Yellow': ['Shana', 'Kishan','Tim', 'Steve','Nik','Martin','Sam']}

In [46]:
d

{'Blue': ['Jan', 'Matt', 'Jonathan', 'Tan', 'Wayne', 'Michal', 'Callum'],
 'Yellow': ['Shana', 'Kishan', 'Tim', 'Steve', 'Nik', 'Martin', 'Sam']}

In [47]:
d['Blue']

['Jan', 'Matt', 'Jonathan', 'Tan', 'Wayne', 'Michal', 'Callum']

In [48]:
d['Yellow'][1]

'Kishan'

### Importing a Module

To use a module/library/package in Python, we first have to import it. 

In [20]:
import math

There are different ways to import libraries. 

For example:

##### import pandas 
imports the pandas module under the pandas namespace, so you would need to call objects within pandas using 'pandas.[function]'
For example: panda.DataFrame

##### from pandas import * 
imports all objects from the pandas module into your current namespace, so you would call objects within pandas using only 'DataFrame'. 
###### This could have unexepcted consequences if there are any naming conflicts between your current namespace and the pandas namespace.

##### from pandas import DataFrame 
is the same as above, but only imports DataFrame (instead of everything) into your current namespace.

You can also assign aliases to an import

##### import pandas as pd
imports as the first example above, however you now call objects using 'pd.[function]'
For example: pd.DataFrame

We can have a look at what functions a library contains by running dir() 

In [22]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'trunc']


And help will give a description of the library or each function

In [24]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(...)
        acos(x)
        
        Return the arc cosine (measured in radians) of x.
    
    acosh(...)
        acosh(x)
        
        Return the inverse hyperbolic cosine of x.
    
    asin(...)
        asin(x)
        
        Return the arc sine (measured in radians) of x.
    
    asinh(...)
        asinh(x)
        
        Return the inverse hyperbolic sine of x.
    
    atan(...)
        atan(x)
        
        Return the arc tangent (measured in radians) of x.
    
    atan2(...)
        atan2(y, x)
        
        Return the arc tangent (measured in radians) of y/x.
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(...)
        atanh(x)
        
        Return the inverse hyperbolic tangent of x.
    
    ceil(...)
        ceil(x)
        
 

In [25]:
help(math.asin)

Help on built-in function asin in module math:

asin(...)
    asin(x)
    
    Return the arc sine (measured in radians) of x.



### NumPy

Numpy is a python module that adds support for large, multi-dimensional arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays.

It's very quick and can be much more convenient than using multiple lists.

The numpy array is the main object. It is an array that is homogenous (only takes one type of data) - usually numbers.

In [71]:
import numpy as np

In [79]:
#create a range of numbers using numpy
a = np.arange(15)

In [81]:
b = np.reshape(a,[3,5])

In [83]:
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [84]:
a.mean()

7.0

In [85]:
a.sum()

105

In [96]:
c = np.arange(9).reshape(3,3)*2
d = np.arange(9).reshape(3,3)

In [98]:
print(c)
print(d)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [99]:
c*d

array([[  0,   2,   8],
       [ 18,  32,  50],
       [ 72,  98, 128]])

In [100]:
np.dot(c,d)

array([[ 30,  36,  42],
       [ 84, 108, 132],
       [138, 180, 222]])

### Pandas

pandas is a Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python.

The main object from pandas is called a DataFrame and it can take multiple datatypes. 

This is very similar to a table in Excel

In [102]:
import pandas as pd

In [103]:
pd.DataFrame(c)

0   1   2
0   0   2   4
1   6   8  10
2  12  14  16